apiVersion: v1
kind: Secret
metadata:
  name: harbor-sec
  namespace: cicd
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovLzE5Mi4xNjguMTM3LjEzNyI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJIYXJib3IxMjM0NSIsImF1dGgiOiJZV1J0YVc0Nk1UQXhOQSJ9fX0=
